version: '3'

volumes:
  pg_data_production:
  static_volume:
  static_media:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: asumasuma/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - static_media:/app/media
  frontend:
    image: asumasuma/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: asumasuma/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - static_media:/app/media
    ports:
      - 9000:80 
